/*
 * generated by Xtext
 */
package com.opcoach.training.rental.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RentalDslRuntimeModule extends com.opcoach.training.rental.xtext.AbstractRentalDslRuntimeModule {

}
