/*
* generated by Xtext
*/
package com.opcoach.training.rental.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.opcoach.training.rental.xtext.services.RentalDslGrammarAccess;

public class RentalDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RentalDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.opcoach.training.rental.xtext.parser.antlr.internal.InternalRentalDslParser createParser(XtextTokenStream stream) {
		return new com.opcoach.training.rental.xtext.parser.antlr.internal.InternalRentalDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RentalAgency";
	}
	
	public RentalDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RentalDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
