/*
* generated by Xtext
*/
package com.opcoach.training.rental.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RentalDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class RentalAgencyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RentalAgency");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRentalAgencyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAddressAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAddressAddressParserRuleCall_3_0 = (RuleCall)cAddressAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cObjectsToRentKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cObjectsToRentAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cObjectsToRentRentalObjectParserRuleCall_4_2_0 = (RuleCall)cObjectsToRentAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cObjectsToRentAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cObjectsToRentRentalObjectParserRuleCall_4_3_1_0 = (RuleCall)cObjectsToRentAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCustomersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cCustomersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cCustomersCustomerParserRuleCall_5_2_0 = (RuleCall)cCustomersAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cCustomersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cCustomersCustomerParserRuleCall_5_3_1_0 = (RuleCall)cCustomersAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRentalsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRentalsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cRentalsRentalParserRuleCall_6_2_0 = (RuleCall)cRentalsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRentalsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cRentalsRentalParserRuleCall_6_3_1_0 = (RuleCall)cRentalsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RentalAgency:
		//	"RentalAgency" name=EString "{" address=Address? ("objectsToRent" "{" objectsToRent+=RentalObject (","
		//	objectsToRent+=RentalObject)* "}")? ("customers" "{" customers+=Customer ("," customers+=Customer)* "}")? ("rentals"
		//	"{" rentals+=Rental ("," rentals+=Rental)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"RentalAgency" name=EString "{" address=Address? ("objectsToRent" "{" objectsToRent+=RentalObject (","
		//objectsToRent+=RentalObject)* "}")? ("customers" "{" customers+=Customer ("," customers+=Customer)* "}")? ("rentals"
		//"{" rentals+=Rental ("," rentals+=Rental)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"RentalAgency"
		public Keyword getRentalAgencyKeyword_0() { return cRentalAgencyKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//address=Address?
		public Assignment getAddressAssignment_3() { return cAddressAssignment_3; }

		//Address
		public RuleCall getAddressAddressParserRuleCall_3_0() { return cAddressAddressParserRuleCall_3_0; }

		//("objectsToRent" "{" objectsToRent+=RentalObject ("," objectsToRent+=RentalObject)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"objectsToRent"
		public Keyword getObjectsToRentKeyword_4_0() { return cObjectsToRentKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//objectsToRent+=RentalObject
		public Assignment getObjectsToRentAssignment_4_2() { return cObjectsToRentAssignment_4_2; }

		//RentalObject
		public RuleCall getObjectsToRentRentalObjectParserRuleCall_4_2_0() { return cObjectsToRentRentalObjectParserRuleCall_4_2_0; }

		//("," objectsToRent+=RentalObject)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//objectsToRent+=RentalObject
		public Assignment getObjectsToRentAssignment_4_3_1() { return cObjectsToRentAssignment_4_3_1; }

		//RentalObject
		public RuleCall getObjectsToRentRentalObjectParserRuleCall_4_3_1_0() { return cObjectsToRentRentalObjectParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("customers" "{" customers+=Customer ("," customers+=Customer)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"customers"
		public Keyword getCustomersKeyword_5_0() { return cCustomersKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//customers+=Customer
		public Assignment getCustomersAssignment_5_2() { return cCustomersAssignment_5_2; }

		//Customer
		public RuleCall getCustomersCustomerParserRuleCall_5_2_0() { return cCustomersCustomerParserRuleCall_5_2_0; }

		//("," customers+=Customer)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//customers+=Customer
		public Assignment getCustomersAssignment_5_3_1() { return cCustomersAssignment_5_3_1; }

		//Customer
		public RuleCall getCustomersCustomerParserRuleCall_5_3_1_0() { return cCustomersCustomerParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("rentals" "{" rentals+=Rental ("," rentals+=Rental)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"rentals"
		public Keyword getRentalsKeyword_6_0() { return cRentalsKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//rentals+=Rental
		public Assignment getRentalsAssignment_6_2() { return cRentalsAssignment_6_2; }

		//Rental
		public RuleCall getRentalsRentalParserRuleCall_6_2_0() { return cRentalsRentalParserRuleCall_6_2_0; }

		//("," rentals+=Rental)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//rentals+=Rental
		public Assignment getRentalsAssignment_6_3_1() { return cRentalsAssignment_6_3_1; }

		//Rental
		public RuleCall getRentalsRentalParserRuleCall_6_3_1_0() { return cRentalsRentalParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class AddressElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Address");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAddressAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAddressKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStreetTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cStreetTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cStreetTypeStreetTypeEnumRuleCall_3_1_0 = (RuleCall)cStreetTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNumberKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNumberAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNumberEIntParserRuleCall_4_1_0 = (RuleCall)cNumberAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cZipCodeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cZipCodeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cZipCodeEStringParserRuleCall_5_1_0 = (RuleCall)cZipCodeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCityEStringParserRuleCall_6_1_0 = (RuleCall)cCityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cStreetNameKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cStreetNameAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cStreetNameEStringParserRuleCall_7_1_0 = (RuleCall)cStreetNameAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Address:
		//	{Address} "Address" "{" ("streetType" streetType=StreetType)? ("number" number=EInt)? ("zipCode" zipCode=EString)?
		//	("city" city=EString)? ("streetName" streetName=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Address} "Address" "{" ("streetType" streetType=StreetType)? ("number" number=EInt)? ("zipCode" zipCode=EString)?
		//("city" city=EString)? ("streetName" streetName=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Address}
		public Action getAddressAction_0() { return cAddressAction_0; }

		//"Address"
		public Keyword getAddressKeyword_1() { return cAddressKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("streetType" streetType=StreetType)?
		public Group getGroup_3() { return cGroup_3; }

		//"streetType"
		public Keyword getStreetTypeKeyword_3_0() { return cStreetTypeKeyword_3_0; }

		//streetType=StreetType
		public Assignment getStreetTypeAssignment_3_1() { return cStreetTypeAssignment_3_1; }

		//StreetType
		public RuleCall getStreetTypeStreetTypeEnumRuleCall_3_1_0() { return cStreetTypeStreetTypeEnumRuleCall_3_1_0; }

		//("number" number=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"number"
		public Keyword getNumberKeyword_4_0() { return cNumberKeyword_4_0; }

		//number=EInt
		public Assignment getNumberAssignment_4_1() { return cNumberAssignment_4_1; }

		//EInt
		public RuleCall getNumberEIntParserRuleCall_4_1_0() { return cNumberEIntParserRuleCall_4_1_0; }

		//("zipCode" zipCode=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"zipCode"
		public Keyword getZipCodeKeyword_5_0() { return cZipCodeKeyword_5_0; }

		//zipCode=EString
		public Assignment getZipCodeAssignment_5_1() { return cZipCodeAssignment_5_1; }

		//EString
		public RuleCall getZipCodeEStringParserRuleCall_5_1_0() { return cZipCodeEStringParserRuleCall_5_1_0; }

		//("city" city=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"city"
		public Keyword getCityKeyword_6_0() { return cCityKeyword_6_0; }

		//city=EString
		public Assignment getCityAssignment_6_1() { return cCityAssignment_6_1; }

		//EString
		public RuleCall getCityEStringParserRuleCall_6_1_0() { return cCityEStringParserRuleCall_6_1_0; }

		//("streetName" streetName=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"streetName"
		public Keyword getStreetNameKeyword_7_0() { return cStreetNameKeyword_7_0; }

		//streetName=EString
		public Assignment getStreetNameAssignment_7_1() { return cStreetNameAssignment_7_1; }

		//EString
		public RuleCall getStreetNameEStringParserRuleCall_7_1_0() { return cStreetNameEStringParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class RentalObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RentalObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRentalObjectAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAvailableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cAvailableAvailableKeyword_1_0 = (Keyword)cAvailableAssignment_1.eContents().get(0);
		private final Keyword cRentalObjectKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIDAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIDELongParserRuleCall_3_0 = (RuleCall)cIDAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RentalObject:
		//	{RentalObject} available?="available"? "RentalObject" ID=ELong "{" "name" name=EString "}";
		public ParserRule getRule() { return rule; }

		//{RentalObject} available?="available"? "RentalObject" ID=ELong "{" "name" name=EString "}"
		public Group getGroup() { return cGroup; }

		//{RentalObject}
		public Action getRentalObjectAction_0() { return cRentalObjectAction_0; }

		//available?="available"?
		public Assignment getAvailableAssignment_1() { return cAvailableAssignment_1; }

		//"available"
		public Keyword getAvailableAvailableKeyword_1_0() { return cAvailableAvailableKeyword_1_0; }

		//"RentalObject"
		public Keyword getRentalObjectKeyword_2() { return cRentalObjectKeyword_2; }

		//ID=ELong
		public Assignment getIDAssignment_3() { return cIDAssignment_3; }

		//ELong
		public RuleCall getIDELongParserRuleCall_3_0() { return cIDELongParserRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//"name"
		public Keyword getNameKeyword_5() { return cNameKeyword_5; }

		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }

		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class CustomerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Customer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCustomerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIDELongParserRuleCall_1_0 = (RuleCall)cIDAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFirstNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFirstNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFirstNameEStringParserRuleCall_4_0 = (RuleCall)cFirstNameAssignment_4.eContents().get(0);
		private final Keyword cLastNameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLastNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLastNameEStringParserRuleCall_6_0 = (RuleCall)cLastNameAssignment_6.eContents().get(0);
		private final Assignment cAddressAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAddressAddressParserRuleCall_7_0 = (RuleCall)cAddressAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cLicensesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cLicensesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cLicensesLicenseParserRuleCall_8_2_0 = (RuleCall)cLicensesAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cLicensesAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cLicensesLicenseParserRuleCall_8_3_1_0 = (RuleCall)cLicensesAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Customer:
		//	"Customer" ID=ELong "{" "firstName" firstName=EString "lastName" lastName=EString address=Address? ("licenses" "{"
		//	licenses+=License ("," licenses+=License)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"Customer" ID=ELong "{" "firstName" firstName=EString "lastName" lastName=EString address=Address? ("licenses" "{"
		//licenses+=License ("," licenses+=License)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"Customer"
		public Keyword getCustomerKeyword_0() { return cCustomerKeyword_0; }

		//ID=ELong
		public Assignment getIDAssignment_1() { return cIDAssignment_1; }

		//ELong
		public RuleCall getIDELongParserRuleCall_1_0() { return cIDELongParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"firstName"
		public Keyword getFirstNameKeyword_3() { return cFirstNameKeyword_3; }

		//firstName=EString
		public Assignment getFirstNameAssignment_4() { return cFirstNameAssignment_4; }

		//EString
		public RuleCall getFirstNameEStringParserRuleCall_4_0() { return cFirstNameEStringParserRuleCall_4_0; }

		//"lastName"
		public Keyword getLastNameKeyword_5() { return cLastNameKeyword_5; }

		//lastName=EString
		public Assignment getLastNameAssignment_6() { return cLastNameAssignment_6; }

		//EString
		public RuleCall getLastNameEStringParserRuleCall_6_0() { return cLastNameEStringParserRuleCall_6_0; }

		//address=Address?
		public Assignment getAddressAssignment_7() { return cAddressAssignment_7; }

		//Address
		public RuleCall getAddressAddressParserRuleCall_7_0() { return cAddressAddressParserRuleCall_7_0; }

		//("licenses" "{" licenses+=License ("," licenses+=License)* "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"licenses"
		public Keyword getLicensesKeyword_8_0() { return cLicensesKeyword_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }

		//licenses+=License
		public Assignment getLicensesAssignment_8_2() { return cLicensesAssignment_8_2; }

		//License
		public RuleCall getLicensesLicenseParserRuleCall_8_2_0() { return cLicensesLicenseParserRuleCall_8_2_0; }

		//("," licenses+=License)*
		public Group getGroup_8_3() { return cGroup_8_3; }

		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }

		//licenses+=License
		public Assignment getLicensesAssignment_8_3_1() { return cLicensesAssignment_8_3_1; }

		//License
		public RuleCall getLicensesLicenseParserRuleCall_8_3_1_0() { return cLicensesLicenseParserRuleCall_8_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class RentalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Rental");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRentalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cStartDateKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cStartDateAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cStartDateEDateParserRuleCall_2_1_0 = (RuleCall)cStartDateAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEndDateKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cEndDateAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cEndDateEDateParserRuleCall_3_1_0 = (RuleCall)cEndDateAssignment_3_1.eContents().get(0);
		private final Keyword cCustomerKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCustomerAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cCustomerCustomerCrossReference_5_0 = (CrossReference)cCustomerAssignment_5.eContents().get(0);
		private final RuleCall cCustomerCustomerEStringParserRuleCall_5_0_1 = (RuleCall)cCustomerCustomerCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRentedObjectKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cRentedObjectAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cRentedObjectRentalObjectCrossReference_6_1_0 = (CrossReference)cRentedObjectAssignment_6_1.eContents().get(0);
		private final RuleCall cRentedObjectRentalObjectEStringParserRuleCall_6_1_0_1 = (RuleCall)cRentedObjectRentalObjectCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Rental:
		//	"Rental" "{" ("startDate" startDate=EDate)? ("endDate" endDate=EDate)? "customer" customer=[Customer|EString]
		//	("rentedObject" rentedObject=[RentalObject|EString])? "}";
		public ParserRule getRule() { return rule; }

		//"Rental" "{" ("startDate" startDate=EDate)? ("endDate" endDate=EDate)? "customer" customer=[Customer|EString]
		//("rentedObject" rentedObject=[RentalObject|EString])? "}"
		public Group getGroup() { return cGroup; }

		//"Rental"
		public Keyword getRentalKeyword_0() { return cRentalKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("startDate" startDate=EDate)?
		public Group getGroup_2() { return cGroup_2; }

		//"startDate"
		public Keyword getStartDateKeyword_2_0() { return cStartDateKeyword_2_0; }

		//startDate=EDate
		public Assignment getStartDateAssignment_2_1() { return cStartDateAssignment_2_1; }

		//EDate
		public RuleCall getStartDateEDateParserRuleCall_2_1_0() { return cStartDateEDateParserRuleCall_2_1_0; }

		//("endDate" endDate=EDate)?
		public Group getGroup_3() { return cGroup_3; }

		//"endDate"
		public Keyword getEndDateKeyword_3_0() { return cEndDateKeyword_3_0; }

		//endDate=EDate
		public Assignment getEndDateAssignment_3_1() { return cEndDateAssignment_3_1; }

		//EDate
		public RuleCall getEndDateEDateParserRuleCall_3_1_0() { return cEndDateEDateParserRuleCall_3_1_0; }

		//"customer"
		public Keyword getCustomerKeyword_4() { return cCustomerKeyword_4; }

		//customer=[Customer|EString]
		public Assignment getCustomerAssignment_5() { return cCustomerAssignment_5; }

		//[Customer|EString]
		public CrossReference getCustomerCustomerCrossReference_5_0() { return cCustomerCustomerCrossReference_5_0; }

		//EString
		public RuleCall getCustomerCustomerEStringParserRuleCall_5_0_1() { return cCustomerCustomerEStringParserRuleCall_5_0_1; }

		//("rentedObject" rentedObject=[RentalObject|EString])?
		public Group getGroup_6() { return cGroup_6; }

		//"rentedObject"
		public Keyword getRentedObjectKeyword_6_0() { return cRentedObjectKeyword_6_0; }

		//rentedObject=[RentalObject|EString]
		public Assignment getRentedObjectAssignment_6_1() { return cRentedObjectAssignment_6_1; }

		//[RentalObject|EString]
		public CrossReference getRentedObjectRentalObjectCrossReference_6_1_0() { return cRentedObjectRentalObjectCrossReference_6_1_0; }

		//EString
		public RuleCall getRentedObjectRentalObjectEStringParserRuleCall_6_1_0_1() { return cRentedObjectRentalObjectEStringParserRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class ELongElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ELong");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//ELong returns ecore::ELong:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class LicenseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "License");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLicenseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLicenseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNumberKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNumberAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNumberEIntParserRuleCall_3_1_0 = (RuleCall)cNumberAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValidityDateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValidityDateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValidityDateEDateParserRuleCall_4_1_0 = (RuleCall)cValidityDateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEReference0Keyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cEReference0Assignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cEReference0CustomerCrossReference_5_1_0 = (CrossReference)cEReference0Assignment_5_1.eContents().get(0);
		private final RuleCall cEReference0CustomerEStringParserRuleCall_5_1_0_1 = (RuleCall)cEReference0CustomerCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//License:
		//	{License} "License" "{" ("number" number=EInt)? ("validityDate" validityDate=EDate)? ("EReference0"
		//	EReference0=[Customer|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{License} "License" "{" ("number" number=EInt)? ("validityDate" validityDate=EDate)? ("EReference0"
		//EReference0=[Customer|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{License}
		public Action getLicenseAction_0() { return cLicenseAction_0; }

		//"License"
		public Keyword getLicenseKeyword_1() { return cLicenseKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("number" number=EInt)?
		public Group getGroup_3() { return cGroup_3; }

		//"number"
		public Keyword getNumberKeyword_3_0() { return cNumberKeyword_3_0; }

		//number=EInt
		public Assignment getNumberAssignment_3_1() { return cNumberAssignment_3_1; }

		//EInt
		public RuleCall getNumberEIntParserRuleCall_3_1_0() { return cNumberEIntParserRuleCall_3_1_0; }

		//("validityDate" validityDate=EDate)?
		public Group getGroup_4() { return cGroup_4; }

		//"validityDate"
		public Keyword getValidityDateKeyword_4_0() { return cValidityDateKeyword_4_0; }

		//validityDate=EDate
		public Assignment getValidityDateAssignment_4_1() { return cValidityDateAssignment_4_1; }

		//EDate
		public RuleCall getValidityDateEDateParserRuleCall_4_1_0() { return cValidityDateEDateParserRuleCall_4_1_0; }

		//("EReference0" EReference0=[Customer|EString])?
		public Group getGroup_5() { return cGroup_5; }

		//"EReference0"
		public Keyword getEReference0Keyword_5_0() { return cEReference0Keyword_5_0; }

		//EReference0=[Customer|EString]
		public Assignment getEReference0Assignment_5_1() { return cEReference0Assignment_5_1; }

		//[Customer|EString]
		public CrossReference getEReference0CustomerCrossReference_5_1_0() { return cEReference0CustomerCrossReference_5_1_0; }

		//EString
		public RuleCall getEReference0CustomerEStringParserRuleCall_5_1_0_1() { return cEReference0CustomerEStringParserRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDate");
		private final Keyword cEDateKeyword = (Keyword)rule.eContents().get(1);
		
		/// * TODO: implement this rule and an appropriate IValueConverter * / EDate returns ecore::EDate:
		//	"EDate";
		public ParserRule getRule() { return rule; }

		//"EDate"
		public Keyword getEDateKeyword() { return cEDateKeyword; }
	}
	
	
	public class StreetTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "StreetType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStreetEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStreetStreetKeyword_0_0 = (Keyword)cStreetEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRoadEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRoadRoadKeyword_1_0 = (Keyword)cRoadEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum StreetType:
		//	Street | Road;
		public EnumRule getRule() { return rule; }

		//Street | Road
		public Alternatives getAlternatives() { return cAlternatives; }

		//Street
		public EnumLiteralDeclaration getStreetEnumLiteralDeclaration_0() { return cStreetEnumLiteralDeclaration_0; }

		//"Street"
		public Keyword getStreetStreetKeyword_0_0() { return cStreetStreetKeyword_0_0; }

		//Road
		public EnumLiteralDeclaration getRoadEnumLiteralDeclaration_1() { return cRoadEnumLiteralDeclaration_1; }

		//"Road"
		public Keyword getRoadRoadKeyword_1_0() { return cRoadRoadKeyword_1_0; }
	}
	
	private final RentalAgencyElements pRentalAgency;
	private final EStringElements pEString;
	private final AddressElements pAddress;
	private final RentalObjectElements pRentalObject;
	private final CustomerElements pCustomer;
	private final RentalElements pRental;
	private final StreetTypeElements unknownRuleStreetType;
	private final EIntElements pEInt;
	private final ELongElements pELong;
	private final EBooleanElements pEBoolean;
	private final LicenseElements pLicense;
	private final EDateElements pEDate;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RentalDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRentalAgency = new RentalAgencyElements();
		this.pEString = new EStringElements();
		this.pAddress = new AddressElements();
		this.pRentalObject = new RentalObjectElements();
		this.pCustomer = new CustomerElements();
		this.pRental = new RentalElements();
		this.unknownRuleStreetType = new StreetTypeElements();
		this.pEInt = new EIntElements();
		this.pELong = new ELongElements();
		this.pEBoolean = new EBooleanElements();
		this.pLicense = new LicenseElements();
		this.pEDate = new EDateElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.opcoach.training.rental.xtext.RentalDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RentalAgency:
	//	"RentalAgency" name=EString "{" address=Address? ("objectsToRent" "{" objectsToRent+=RentalObject (","
	//	objectsToRent+=RentalObject)* "}")? ("customers" "{" customers+=Customer ("," customers+=Customer)* "}")? ("rentals"
	//	"{" rentals+=Rental ("," rentals+=Rental)* "}")? "}";
	public RentalAgencyElements getRentalAgencyAccess() {
		return pRentalAgency;
	}
	
	public ParserRule getRentalAgencyRule() {
		return getRentalAgencyAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Address:
	//	{Address} "Address" "{" ("streetType" streetType=StreetType)? ("number" number=EInt)? ("zipCode" zipCode=EString)?
	//	("city" city=EString)? ("streetName" streetName=EString)? "}";
	public AddressElements getAddressAccess() {
		return pAddress;
	}
	
	public ParserRule getAddressRule() {
		return getAddressAccess().getRule();
	}

	//RentalObject:
	//	{RentalObject} available?="available"? "RentalObject" ID=ELong "{" "name" name=EString "}";
	public RentalObjectElements getRentalObjectAccess() {
		return pRentalObject;
	}
	
	public ParserRule getRentalObjectRule() {
		return getRentalObjectAccess().getRule();
	}

	//Customer:
	//	"Customer" ID=ELong "{" "firstName" firstName=EString "lastName" lastName=EString address=Address? ("licenses" "{"
	//	licenses+=License ("," licenses+=License)* "}")? "}";
	public CustomerElements getCustomerAccess() {
		return pCustomer;
	}
	
	public ParserRule getCustomerRule() {
		return getCustomerAccess().getRule();
	}

	//Rental:
	//	"Rental" "{" ("startDate" startDate=EDate)? ("endDate" endDate=EDate)? "customer" customer=[Customer|EString]
	//	("rentedObject" rentedObject=[RentalObject|EString])? "}";
	public RentalElements getRentalAccess() {
		return pRental;
	}
	
	public ParserRule getRentalRule() {
		return getRentalAccess().getRule();
	}

	//enum StreetType:
	//	Street | Road;
	public StreetTypeElements getStreetTypeAccess() {
		return unknownRuleStreetType;
	}
	
	public EnumRule getStreetTypeRule() {
		return getStreetTypeAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//ELong returns ecore::ELong:
	//	"-"? INT;
	public ELongElements getELongAccess() {
		return pELong;
	}
	
	public ParserRule getELongRule() {
		return getELongAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//License:
	//	{License} "License" "{" ("number" number=EInt)? ("validityDate" validityDate=EDate)? ("EReference0"
	//	EReference0=[Customer|EString])? "}";
	public LicenseElements getLicenseAccess() {
		return pLicense;
	}
	
	public ParserRule getLicenseRule() {
		return getLicenseAccess().getRule();
	}

	/// * TODO: implement this rule and an appropriate IValueConverter * / EDate returns ecore::EDate:
	//	"EDate";
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
