/**
 *
 * $Id$
 */
package com.opcoach.training.rental.validation;

import com.opcoach.training.rental.StreetType;

/**
 * A sample validator interface for {@link com.opcoach.training.rental.Address}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AddressValidator {
	boolean validate();

	boolean validateStreetType(StreetType value);
	boolean validateNumber(int value);
	boolean validateZipCode(String value);
	boolean validateCity(String value);
	boolean validateStreetName(String value);
}
