/**
 *
 * $Id$
 */
package com.opcoach.training.rental.validation;

import com.opcoach.training.rental.Address;
import com.opcoach.training.rental.License;
import com.opcoach.training.rental.RentalAgency;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.opcoach.training.rental.Customer}
 * . This doesn't really do anything, and it's not a real EMF artifact. It was
 * generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled
 * with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CustomerValidator
{
	boolean validate();

	boolean validateFirstName(String value);

	boolean validateLastName(String value);

	boolean validateAddress(Address value);

	boolean validateLicenses(EList<License> value);

	boolean validateParentAgency(RentalAgency value);

	boolean validateID(long value);
}
