/**
 *
 * $Id$
 */
package com.opcoach.training.rental.validation;

import com.opcoach.training.rental.Customer;
import com.opcoach.training.rental.RentalAgency;
import com.opcoach.training.rental.RentalObject;

import java.util.Date;

/**
 * A sample validator interface for {@link com.opcoach.training.rental.Rental}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RentalValidator {
	boolean validate();

	boolean validateCustomer(Customer value);
	boolean validateRentedObject(RentalObject value);
	boolean validateStartDate(Date value);
	boolean validateEndDate(Date value);
	boolean validateParentAgency(RentalAgency value);
}
