/**
 *
 * $Id$
 */
package com.opcoach.training.rental.validation;

import com.opcoach.training.rental.RentalAgency;

/**
 * A sample validator interface for
 * {@link com.opcoach.training.rental.RentalObject}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RentalObjectValidator
{
	boolean validate();

	boolean validateID(long value);

	boolean validateName(String value);

	boolean validateParentAgency(RentalAgency value);

	boolean validateAvailable(boolean value);
}
