/*
 * generated by Xtext
 */
package com.opcoach.training.rental.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RentalDslUiModule extends com.opcoach.training.rental.xtext.ui.AbstractRentalDslUiModule {
	public RentalDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
