/*
* generated by Xtext
*/
package com.opcoach.training.rental.xtext.ui.contentassist;

import com.opcoach.training.rental.xtext.ui.contentassist.AbstractRentalDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RentalDslProposalProvider extends AbstractRentalDslProposalProvider {

}
